[project]
name = "online-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M.ghasemi", email = "mghasemi13786@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings>=2.15.0",
    "pymongo>=4.11.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
